openapi: 3.0.3
info:
  title: Source Record API
  version: 1.0.0
  description: API for managing source records associated with forms.

paths:
  /sources:
    post:
      summary: Create a new source record
      operationId: createSourceRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceRecord'
      responses:
        '201':
          description: Source record created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceRecord'
        '500':
          description: Failed to create source record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /sources/{id}:
    get:
      summary: Get source records by form ID
      operationId: getSourceRecordsByFormId
      parameters:
        - name: id
          in: path
          required: true
          description: The form ID to retrieve source records for
          schema:
            type: string
      responses:
        '200':
          description: List of source records for the given form
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SourceRecord'
        '500':
          description: Failed to fetch source records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    SourceRecord:
      type: object
      properties:
        id:
          type: string
        formId:
          type: string
        sourceData:
          type: object
      required:
        - formId
        - sourceData

    Error:
      type: object
      properties:
        message:
          type: string
